/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_liaohailong_pdftestapp_JNI */

#ifndef _Included_org_liaohailong_pdftestapp_JNI
#define _Included_org_liaohailong_pdftestapp_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_liaohailong_pdftestapp_JNI
 * Method:    getHelloWord
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_liaohailong_pdftestapp_JNI_getHelloWord
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
